version: '3'

services:
  web:
    image: nginx:latest
    depends_on:
      - php
    volumes:
      - .:/var/www:rw
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www:rw
      - ./docker/php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php/config/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - 9000